name: CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.9.0
      with:
        access_token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Checkout Repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # fetch all history
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Get Last Commit Date
      id: date
      run: echo "::set-output name=date::$(git log -1 --format="%at" | xargs -I{} date -d @{} +%Y%m%d_%H%M%S)"

    - name: Get Changelog
      id: changelog
      run: |
        CHANGELOG_ENV=$(git log --pretty=format:"%an: %s" | ./scripts/filter_changelog.py | jq --raw-input --slurp '.' | sed 's/^\"\"$/CANCEL/g')
        echo "$CHANGELOG_ENV"

        echo "::set-output name=RELEASE_BODY::$CHANGELOG_ENV"

    - name: Debug
      run: |
        echo "RELEASE_BODY: " ${{ steps.changelog.outputs.RELEASE_BODY }}

    - name: Kick off Cancelling(if need)
      uses: andymckay/cancel-action@0.2
      if: steps.changelog.outputs.RELEASE_BODY == 'CANCEL'

    - name: Waiting for Cancellation
      run: sleep 30
      if: steps.changelog.outputs.RELEASE_BODY == 'CANCEL'

    - uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2

    - name: Build Repo
      run: ./gradlew --no-daemon build

    - name: Upload APKs to Release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./app/build/outputs/apk/release/*.apk
        tag: release.${{ steps.date.outputs.date }}
        overwrite: true
        file_glob: true
        body: |
          Changelog since last release:
          ```
          ${{ fromJSON(steps.changelog.outputs.RELEASE_BODY) }}
          ```
